# Generated by Django 5.0.6 on 2024-05-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('codigo_autor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('codigo_editorial', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo_libro', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_libro', models.CharField(max_length=50)),
                ('existencias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('codigo_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.autor')),
                ('codigo_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.editorial')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genero')),
            ],
        ),
    ]
